list: $/marpo/comic/models/chapters/columns.yaml
modelClass: Marpo\Comic\Models\Chapters
title: Chapters
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'marpo/comic/chapters/update/:id'
