list: $/marpo/comic/models/pages/columns.yaml
modelClass: Marpo\Comic\Models\Pages
title: Pages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'marpo/comic/pages/update/:id'
